# Generated by Django 4.2.6 on 2024-06-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('stock', models.IntegerField()),
                ('area', models.CharField(choices=[('COCINA', 'Cocina'), ('ASEO', 'Aseo'), ('COMEDOR', 'Comedor')], max_length=10)),
            ],
        ),
    ]
